# Generated by Django 3.2 on 2021-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
