# Generated by Django 3.2 on 2021-05-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0006_auto_20210504_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
