# Generated by Django 3.2 on 2021-05-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0007_auto_20210504_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Uncategorized', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Overview.productcategory'),
        ),
    ]
